version: "3"
networks:
  mjevents:

services:
  events-db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mjevents

  bookings-db:
    image: mongo
    networks:
      - mjevents

  events:
    build:
      context: .
      dockerfile: Dockerfile.eventservice
    ports:
      - 8181:8181
      - 9100:9100
    depends_on:
      - rabbitmq
      - events-db
    environment:
      - AMQP_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGO_URL=mongodb://events-db/events
    networks:
      - mjevents

  bookings:
    build:
      context: .
      dockerfile: Dockerfile.bookingservice
    ports:
      - 8282:8181
      - 9101:9100
    depends_on:
      - rabbitmq
      - bookings-db
    environment:
      - AMQP_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGO_URL=mongodb://bookings-db/bookings
    networks:
      - mjevents

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
        - mjevents

  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"


  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redisdata:/data
