version: "3"
networks:
  mjevents:

services:
  events-db:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
